// GENERATED by tools/generate_entity_graph.mjs — do not edit by hand.
// 2026-07-11T02:38:13.119Z · 271 nodes · 363 edges
export const GRAPH = {
 "nodes": [
  {
   "id": "js/art.js",
   "label": "art.js",
   "cat": "module",
   "path": "js/art.js",
   "desc": "ArtManager — hangs artworks, streams images as you approach, click hit-testing.",
   "deg": 9,
   "size": 3.55
  },
  {
   "id": "js/audio.js",
   "label": "audio.js",
   "cat": "module",
   "path": "js/audio.js",
   "desc": "Procedural ambient music and per-room soundscapes (WebAudio).",
   "deg": 2,
   "size": 2.84
  },
  {
   "id": "js/controls.js",
   "label": "controls.js",
   "cat": "module",
   "path": "js/controls.js",
   "desc": "First-person movement: pointer & touch look, glide, collision clamping.",
   "deg": 3,
   "size": 2.98
  },
  {
   "id": "js/corridor.js",
   "label": "corridor.js",
   "cat": "module",
   "path": "js/corridor.js",
   "desc": "Builds each hall era by era — walls, bands, columns, portals, decor, end lights.",
   "deg": 36,
   "size": 4.9
  },
  {
   "id": "js/device.js",
   "label": "device.js",
   "cat": "module",
   "path": "js/device.js",
   "desc": "Mobile detection and the QUALITY performance profile.",
   "deg": 3,
   "size": 2.98
  },
  {
   "id": "js/fire.js",
   "label": "fire.js",
   "cat": "module",
   "path": "js/fire.js",
   "desc": "Animated flame sprites, torches and campfires.",
   "deg": 5,
   "size": 3.21
  },
  {
   "id": "js/main.js",
   "label": "main.js",
   "cat": "module",
   "path": "js/main.js",
   "desc": "Entry point — renderer, camera, the main loop, light culling, resume wiring.",
   "deg": 8,
   "size": 3.47
  },
  {
   "id": "js/models.js",
   "label": "models.js",
   "cat": "module",
   "path": "js/models.js",
   "desc": "GLTFLoader wrapper — spawns named parts out of the era architecture kits.",
   "deg": 4,
   "size": 3.1
  },
  {
   "id": "js/persist.js",
   "label": "persist.js",
   "cat": "module",
   "path": "js/persist.js",
   "desc": "Saves and restores the visitor's position in localStorage.",
   "deg": 2,
   "size": 2.84
  },
  {
   "id": "js/styles.js",
   "label": "styles.js",
   "cat": "module",
   "path": "js/styles.js",
   "desc": "Era style definitions — materials, friezes, columns, portals, kit references.",
   "deg": 5,
   "size": 3.21
  },
  {
   "id": "js/textures.js",
   "label": "textures.js",
   "cat": "module",
   "path": "js/textures.js",
   "desc": "Procedural canvas texture library (~50 generators) plus the file-texture loader.",
   "deg": 7,
   "size": 3.39
  },
  {
   "id": "js/ui.js",
   "label": "ui.js",
   "cat": "module",
   "path": "js/ui.js",
   "desc": "Intro splash, HUD era chip, artwork info panel, fullscreen image zoomer.",
   "deg": 5,
   "size": 3.21
  },
  {
   "id": "js/world.js",
   "label": "world.js",
   "cat": "module",
   "path": "js/world.js",
   "desc": "Assembles the museum: rotunda hub, entrance cave, six wings, collision + locate().",
   "deg": 18,
   "size": 4.11
  },
  {
   "id": "js/data/africa.js",
   "label": "africa.js",
   "cat": "data",
   "path": "js/data/africa.js",
   "desc": "20 works for the Africa wing.",
   "deg": 2,
   "size": 2.54
  },
  {
   "id": "js/data/americas.js",
   "label": "americas.js",
   "cat": "data",
   "path": "js/data/americas.js",
   "desc": "20 works for the The Americas wing.",
   "deg": 2,
   "size": 2.54
  },
  {
   "id": "js/data/artworks.js",
   "label": "artworks.js",
   "cat": "data",
   "path": "js/data/artworks.js",
   "desc": "Master index — ERAS metadata, REGIONS wing layout, ALL_ARTWORKS.",
   "deg": 10,
   "size": 3.32
  },
  {
   "id": "js/data/asia.js",
   "label": "asia.js",
   "cat": "data",
   "path": "js/data/asia.js",
   "desc": "30 works for the Asia wing.",
   "deg": 2,
   "size": 2.54
  },
  {
   "id": "js/data/europe.js",
   "label": "europe.js",
   "cat": "data",
   "path": "js/data/europe.js",
   "desc": "40 works for the Europe wing.",
   "deg": 2,
   "size": 2.54
  },
  {
   "id": "js/data/imageLocal.js",
   "label": "imageLocal.js",
   "cat": "data",
   "path": "js/data/imageLocal.js",
   "desc": "Map of locally bundled artwork images.",
   "deg": 3,
   "size": 2.68
  },
  {
   "id": "js/data/imageUrls.js",
   "label": "imageUrls.js",
   "cat": "data",
   "path": "js/data/imageUrls.js",
   "desc": "Generated map of Wikimedia Commons image URLs (tools/resolve_images.py).",
   "deg": 3,
   "size": 2.68
  },
  {
   "id": "js/data/middleeast.js",
   "label": "middleeast.js",
   "cat": "data",
   "path": "js/data/middleeast.js",
   "desc": "40 works for the The Middle East wing.",
   "deg": 2,
   "size": 2.54
  },
  {
   "id": "js/data/oceania.js",
   "label": "oceania.js",
   "cat": "data",
   "path": "js/data/oceania.js",
   "desc": "12 works for the Oceania wing.",
   "deg": 2,
   "size": 2.54
  },
  {
   "id": "js/data/prehistoric.js",
   "label": "prehistoric.js",
   "cat": "data",
   "path": "js/data/prehistoric.js",
   "desc": "10 works displayed in the entrance cave.",
   "deg": 2,
   "size": 2.54
  },
  {
   "id": "lib:three",
   "label": "Three.js",
   "cat": "asset",
   "desc": "WebGL 3D engine, v0.160 via the CDN import map.",
   "deg": 9,
   "size": 2.85
  },
  {
   "id": "concept:museum",
   "label": "Timeline of Art Museum",
   "cat": "concept",
   "desc": "The whole walkable scene — cave, rotunda, six wings, 40,000 years of art.",
   "deg": 10,
   "size": 3.42
  },
  {
   "id": "concept:rotunda",
   "label": "Grand Crossing (Rotunda)",
   "cat": "concept",
   "desc": "Domed hub where the six wings meet; you return here from every end light.",
   "deg": 2,
   "size": 2.64
  },
  {
   "id": "concept:cave",
   "label": "Prehistoric Cave",
   "cat": "concept",
   "desc": "Firelit entrance cave — the spawn point, hung with the first artworks.",
   "deg": 13,
   "size": 3.62
  },
  {
   "id": "concept:player",
   "label": "Visitor (Player)",
   "cat": "concept",
   "desc": "First-person camera at eye height 1.62 m, collision-clamped to the halls.",
   "deg": 1,
   "size": 2.45
  },
  {
   "id": "concept:styles",
   "label": "Era Styles",
   "cat": "concept",
   "desc": "31 architecture styles keyed by era — walls, floors, portals, kits.",
   "deg": 1,
   "size": 2.45
  },
  {
   "id": "concept:portals",
   "label": "Portals & End Lights",
   "cat": "concept",
   "desc": "Era doorways with signs, and the light curtains that carry you back to the hub.",
   "deg": 1,
   "size": 2.45
  },
  {
   "id": "concept:hud",
   "label": "HUD & Info Panel",
   "cat": "concept",
   "desc": "Era chip, hint bar, artwork panel and fullscreen zoomer overlays.",
   "deg": 1,
   "size": 2.45
  },
  {
   "id": "concept:audio",
   "label": "Music & Room Audio",
   "cat": "concept",
   "desc": "Procedural ambient score that shifts per room and era.",
   "deg": 1,
   "size": 2.45
  },
  {
   "id": "concept:save",
   "label": "Saved Position",
   "cat": "concept",
   "desc": "localStorage resume point — validated against collision before restoring.",
   "deg": 1,
   "size": 2.45
  },
  {
   "id": "concept:quality",
   "label": "Quality Profile",
   "cat": "concept",
   "desc": "Device-based performance settings: pixel ratio cap, texture sizes, light budget.",
   "deg": 1,
   "size": 2.45
  },
  {
   "id": "concept:fires",
   "label": "Fires & Torches",
   "cat": "concept",
   "desc": "Animated flames lighting the cave and rotunda.",
   "deg": 1,
   "size": 2.45
  },
  {
   "id": "concept:kits",
   "label": "Architecture Kits",
   "cat": "concept",
   "desc": "Blender GLB decor kits — one per era style, streamed in as named parts.",
   "deg": 25,
   "size": 4.25
  },
  {
   "id": "kit:adobe",
   "label": "adobe.glb",
   "cat": "asset",
   "path": "assets/models/adobe.glb",
   "desc": "Blender architecture kit (portal, decor, props).",
   "deg": 2,
   "size": 2.14
  },
  {
   "id": "kit:amsalon",
   "label": "amsalon.glb",
   "cat": "asset",
   "path": "assets/models/amsalon.glb",
   "desc": "Blender architecture kit (portal, decor, props).",
   "deg": 2,
   "size": 2.14
  },
  {
   "id": "kit:baroque",
   "label": "baroque.glb",
   "cat": "asset",
   "path": "assets/models/baroque.glb",
   "desc": "Blender architecture kit (portal, decor, props).",
   "deg": 2,
   "size": 2.14
  },
  {
   "id": "kit:china",
   "label": "china.glb",
   "cat": "asset",
   "path": "assets/models/china.glb",
   "desc": "Blender architecture kit (portal, decor, props).",
   "deg": 2,
   "size": 2.14
  },
  {
   "id": "kit:egypt",
   "label": "egypt.glb",
   "cat": "asset",
   "path": "assets/models/egypt.glb",
   "desc": "Blender architecture kit (portal, decor, props).",
   "deg": 2,
   "size": 2.14
  },
  {
   "id": "kit:gothic",
   "label": "gothic.glb",
   "cat": "asset",
   "path": "assets/models/gothic.glb",
   "desc": "Blender architecture kit (portal, decor, props).",
   "deg": 2,
   "size": 2.14
  },
  {
   "id": "kit:greek",
   "label": "greek.glb",
   "cat": "asset",
   "path": "assets/models/greek.glb",
   "desc": "Blender architecture kit (portal, decor, props).",
   "deg": 2,
   "size": 2.14
  },
  {
   "id": "kit:inca",
   "label": "inca.glb",
   "cat": "asset",
   "path": "assets/models/inca.glb",
   "desc": "Blender architecture kit (portal, decor, props).",
   "deg": 2,
   "size": 2.14
  },
  {
   "id": "kit:indus",
   "label": "indus.glb",
   "cat": "asset",
   "path": "assets/models/indus.glb",
   "desc": "Blender architecture kit (portal, decor, props).",
   "deg": 2,
   "size": 2.14
  },
  {
   "id": "kit:islamic",
   "label": "islamic.glb",
   "cat": "asset",
   "path": "assets/models/islamic.glb",
   "desc": "Blender architecture kit (portal, decor, props).",
   "deg": 2,
   "size": 2.14
  },
  {
   "id": "kit:japan",
   "label": "japan.glb",
   "cat": "asset",
   "path": "assets/models/japan.glb",
   "desc": "Blender architecture kit (portal, decor, props).",
   "deg": 2,
   "size": 2.14
  },
  {
   "id": "kit:khmer",
   "label": "khmer.glb",
   "cat": "asset",
   "path": "assets/models/khmer.glb",
   "desc": "Blender architecture kit (portal, decor, props).",
   "deg": 2,
   "size": 2.14
  },
  {
   "id": "kit:kingdoms",
   "label": "kingdoms.glb",
   "cat": "asset",
   "path": "assets/models/kingdoms.glb",
   "desc": "Blender architecture kit (portal, decor, props).",
   "deg": 2,
   "size": 2.14
  },
  {
   "id": "kit:meso",
   "label": "meso.glb",
   "cat": "asset",
   "path": "assets/models/meso.glb",
   "desc": "Blender architecture kit (portal, decor, props).",
   "deg": 2,
   "size": 2.14
  },
  {
   "id": "kit:mesopotamia",
   "label": "mesopotamia.glb",
   "cat": "asset",
   "path": "assets/models/mesopotamia.glb",
   "desc": "Blender architecture kit (portal, decor, props).",
   "deg": 2,
   "size": 2.14
  },
  {
   "id": "kit:modern",
   "label": "modern.glb",
   "cat": "asset",
   "path": "assets/models/modern.glb",
   "desc": "Blender architecture kit (portal, decor, props).",
   "deg": 3,
   "size": 2.28
  },
  {
   "id": "kit:mughal",
   "label": "mughal.glb",
   "cat": "asset",
   "path": "assets/models/mughal.glb",
   "desc": "Blender architecture kit (portal, decor, props).",
   "deg": 2,
   "size": 2.14
  },
  {
   "id": "kit:oceanic",
   "label": "oceanic.glb",
   "cat": "asset",
   "path": "assets/models/oceanic.glb",
   "desc": "Blender architecture kit (portal, decor, props).",
   "deg": 3,
   "size": 2.28
  },
  {
   "id": "kit:persia",
   "label": "persia.glb",
   "cat": "asset",
   "path": "assets/models/persia.glb",
   "desc": "Blender architecture kit (portal, decor, props).",
   "deg": 2,
   "size": 2.14
  },
  {
   "id": "kit:prehistoric",
   "label": "prehistoric.glb",
   "cat": "asset",
   "path": "assets/models/prehistoric.glb",
   "desc": "Blender architecture kit (portal, decor, props).",
   "deg": 2,
   "size": 2.14
  },
  {
   "id": "kit:renaissance",
   "label": "renaissance.glb",
   "cat": "asset",
   "path": "assets/models/renaissance.glb",
   "desc": "Blender architecture kit (portal, decor, props).",
   "deg": 2,
   "size": 2.14
  },
  {
   "id": "kit:rockshelter",
   "label": "rockshelter.glb",
   "cat": "asset",
   "path": "assets/models/rockshelter.glb",
   "desc": "Blender architecture kit (portal, decor, props).",
   "deg": 2,
   "size": 2.14
  },
  {
   "id": "kit:salon",
   "label": "salon.glb",
   "cat": "asset",
   "path": "assets/models/salon.glb",
   "desc": "Blender architecture kit (portal, decor, props).",
   "deg": 2,
   "size": 2.14
  },
  {
   "id": "kit:traditions",
   "label": "traditions.glb",
   "cat": "asset",
   "path": "assets/models/traditions.glb",
   "desc": "Blender architecture kit (portal, decor, props).",
   "deg": 2,
   "size": 2.14
  },
  {
   "id": "asset:texfiles",
   "label": "Texture Files",
   "cat": "asset",
   "path": "assets/textures/",
   "desc": "112 baked surface images (FLUX pipeline), with procedural fallbacks.",
   "deg": 1,
   "size": 1.95
  },
  {
   "id": "asset:wikimedia",
   "label": "Wikimedia Images",
   "cat": "asset",
   "desc": "Remote artwork images, streamed from Wikimedia Commons as you approach.",
   "deg": 2,
   "size": 2.14
  },
  {
   "id": "asset:localart",
   "label": "Local Images",
   "cat": "asset",
   "path": "assets/art/",
   "desc": "Locally bundled artwork images that override remote URLs.",
   "deg": 2,
   "size": 2.14
  },
  {
   "id": "wing:americas",
   "label": "The Americas Wing",
   "cat": "concept",
   "desc": "Hall at -75° from the rotunda — 20 works, moving forward in time.",
   "deg": 8,
   "size": 3.27
  },
  {
   "id": "era:mesoamerica",
   "label": "Mesoamerica",
   "cat": "concept",
   "desc": "1200 BCE – 1520 CE · \"meso\" architecture · 7 works.",
   "deg": 10,
   "size": 3.42
  },
  {
   "id": "art:am-01",
   "label": "Olmec Colossal Head",
   "cat": "art",
   "path": "js/data/americas.js",
   "desc": "Olmec culture, Mexico — c. 1200–900 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:am-02",
   "label": "Pyramid of the Sun, Teotihuacán",
   "cat": "art",
   "path": "js/data/americas.js",
   "desc": "Teotihuacan culture, Mexico — c. 200 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:am-03",
   "label": "Yaxchilán Lintel 24",
   "cat": "art",
   "path": "js/data/americas.js",
   "desc": "Maya culture, Mexico — c. 725 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:am-04",
   "label": "Jade Death Mask of Pakal the Great",
   "cat": "art",
   "path": "js/data/americas.js",
   "desc": "Maya culture, Palenque, Mexico — c. 683 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:am-05",
   "label": "El Castillo, Chichén Itzá",
   "cat": "art",
   "path": "js/data/americas.js",
   "desc": "Maya culture, Yucatán, Mexico — c. 1000 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:am-06",
   "label": "Double-Headed Serpent",
   "cat": "art",
   "path": "js/data/americas.js",
   "desc": "Aztec (Mexica) culture — 15th–16th century CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:am-07",
   "label": "Aztec Sun Stone",
   "cat": "art",
   "path": "js/data/americas.js",
   "desc": "Aztec (Mexica) culture — c. 1502–1520 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "era:andes",
   "label": "The Andes",
   "cat": "concept",
   "desc": "200 BCE – 1530 CE · \"inca\" architecture · 4 works.",
   "deg": 7,
   "size": 3.19
  },
  {
   "id": "art:am-08",
   "label": "Nazca Lines: The Hummingbird",
   "cat": "art",
   "path": "js/data/americas.js",
   "desc": "Nazca culture, Peru — c. 200 BCE – 600 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:am-09",
   "label": "Moche Portrait Vessel",
   "cat": "art",
   "path": "js/data/americas.js",
   "desc": "Moche culture, Peru — c. 100–700 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:am-10",
   "label": "Gate of the Sun, Tiwanaku",
   "cat": "art",
   "path": "js/data/americas.js",
   "desc": "Tiwanaku culture, Bolivia — c. 500–950 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:am-11",
   "label": "Machu Picchu",
   "cat": "art",
   "path": "js/data/americas.js",
   "desc": "Inca Empire, Peru — c. 1450 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "era:nativenorth",
   "label": "Native North America",
   "cat": "concept",
   "desc": "1100–1900 · \"adobe\" architecture · 2 works.",
   "deg": 5,
   "size": 3.01
  },
  {
   "id": "art:am-12",
   "label": "Cliff Palace, Mesa Verde",
   "cat": "art",
   "path": "js/data/americas.js",
   "desc": "Ancestral Puebloans, Colorado, USA — c. 1190–1280 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:am-13",
   "label": "Haida Totem Poles",
   "cat": "art",
   "path": "js/data/americas.js",
   "desc": "Haida and Coast Salish carvers, Pacific Northwest — 19th–20th century CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "era:americas19",
   "label": "The 19th Century",
   "cat": "concept",
   "desc": "1830–1890 · \"amsalon\" architecture · 4 works.",
   "deg": 7,
   "size": 3.19
  },
  {
   "id": "art:am-14",
   "label": "Washington Crossing the Delaware",
   "cat": "art",
   "path": "js/data/americas.js",
   "desc": "Emanuel Leutze — 1851",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:am-15",
   "label": "The Oxbow",
   "cat": "art",
   "path": "js/data/americas.js",
   "desc": "Thomas Cole — 1836",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:am-16",
   "label": "Among the Sierra Nevada, California",
   "cat": "art",
   "path": "js/data/americas.js",
   "desc": "Albert Bierstadt — 1868",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:am-17",
   "label": "Whistler's Mother",
   "cat": "art",
   "path": "js/data/americas.js",
   "desc": "James McNeill Whistler — 1871",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "era:americasmodern",
   "label": "The Modern Era",
   "cat": "concept",
   "desc": "1890–1930 · \"modern\" architecture · 3 works.",
   "deg": 6,
   "size": 3.1
  },
  {
   "id": "art:am-18",
   "label": "The Child's Bath",
   "cat": "art",
   "path": "js/data/americas.js",
   "desc": "Mary Cassatt — 1893",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:am-19",
   "label": "Stag at Sharkey's",
   "cat": "art",
   "path": "js/data/americas.js",
   "desc": "George Bellows — 1909",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:am-20",
   "label": "American Gothic",
   "cat": "art",
   "path": "js/data/americas.js",
   "desc": "Grant Wood — 1930",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "wing:europe",
   "label": "Europe Wing",
   "cat": "concept",
   "desc": "Hall at -45° from the rotunda — 40 works, moving forward in time.",
   "deg": 10,
   "size": 3.42
  },
  {
   "id": "era:classical",
   "label": "Classical Antiquity",
   "cat": "concept",
   "desc": "450 BCE – 100 CE · \"greek\" architecture · 6 works.",
   "deg": 9,
   "size": 3.35
  },
  {
   "id": "art:eu-01",
   "label": "The Parthenon",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Iktinos and Kallikrates, architects — 447–432 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-02",
   "label": "Discobolus (The Discus Thrower)",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "After Myron of Eleutherai — Roman copy of a bronze of c. 450 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-03",
   "label": "Winged Victory of Samothrace",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Unknown Hellenistic sculptor — c. 190 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-04",
   "label": "Venus de Milo",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Attributed to Alexandros of Antioch — c. 130–100 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-05",
   "label": "Laocoön and His Sons",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Agesander, Athenodoros and Polydorus of Rhodes — c. 40–30 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-06",
   "label": "The Alexander Mosaic",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Unknown, after a Greek painting — c. 100 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "era:medieval",
   "label": "Medieval Europe",
   "cat": "concept",
   "desc": "800–1400 · \"gothic\" architecture · 5 works.",
   "deg": 8,
   "size": 3.27
  },
  {
   "id": "art:eu-07",
   "label": "Book of Kells: Chi Rho Page",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Irish monks, probably Iona — c. 800 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-08",
   "label": "The Bayeux Tapestry",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Anglo-Saxon embroiderers — c. 1070 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-09",
   "label": "Notre-Dame de la Belle Verrière",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Unknown glaziers, Chartres Cathedral — 12th–13th century CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-10",
   "label": "Lamentation of Christ",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Giotto di Bondone — c. 1305",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-11",
   "label": "The Wilton Diptych",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Unknown English or French master — c. 1395–1399",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "era:renaissance",
   "label": "The Renaissance",
   "cat": "concept",
   "desc": "1400–1600 · \"renaissance\" architecture · 9 works.",
   "deg": 12,
   "size": 3.56
  },
  {
   "id": "art:eu-12",
   "label": "The Arnolfini Portrait",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Jan van Eyck — 1434",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-13",
   "label": "The Birth of Venus",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Sandro Botticelli — c. 1485",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-14",
   "label": "The Last Supper",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Leonardo da Vinci — 1495–1498",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-15",
   "label": "David",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Michelangelo Buonarroti — 1501–1504",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-16",
   "label": "Mona Lisa",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Leonardo da Vinci — c. 1503–1506",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-17",
   "label": "The School of Athens",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Raphael (Raffaello Sanzio) — 1509–1511",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-18",
   "label": "The Creation of Adam",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Michelangelo Buonarroti — c. 1508–1512",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-19",
   "label": "The Garden of Earthly Delights",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Hieronymus Bosch — c. 1490–1510",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-20",
   "label": "Self-Portrait at Twenty-Eight",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Albrecht Dürer — 1500",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "era:baroque",
   "label": "Baroque & the Golden Age",
   "cat": "concept",
   "desc": "1600–1700 · \"baroque\" architecture · 7 works.",
   "deg": 10,
   "size": 3.42
  },
  {
   "id": "art:eu-21",
   "label": "The Calling of Saint Matthew",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Caravaggio — 1599–1600",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-22",
   "label": "Judith Slaying Holofernes",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Artemisia Gentileschi — c. 1620",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-23",
   "label": "The Ecstasy of Saint Teresa",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Gian Lorenzo Bernini — 1647–1652",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-24",
   "label": "The Night Watch",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Rembrandt van Rijn — 1642",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-25",
   "label": "Las Meninas",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Diego Velázquez — 1656",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-26",
   "label": "The Milkmaid",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Johannes Vermeer — c. 1658–1660",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-27",
   "label": "Girl with a Pearl Earring",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Johannes Vermeer — c. 1665",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "era:romantic",
   "label": "Rococo to Romanticism",
   "cat": "concept",
   "desc": "1750–1850 · \"salon\" architecture · 5 works.",
   "deg": 8,
   "size": 3.27
  },
  {
   "id": "art:eu-28",
   "label": "The Swing",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Jean-Honoré Fragonard — 1767",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-29",
   "label": "The Third of May 1808",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Francisco de Goya — 1814",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-30",
   "label": "The Raft of the Medusa",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Théodore Géricault — 1818–1819",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-31",
   "label": "Wanderer above the Sea of Fog",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Caspar David Friedrich — c. 1818",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-32",
   "label": "Liberty Leading the People",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Eugène Delacroix — 1830",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "era:impressionism",
   "label": "Impressionism & After",
   "cat": "concept",
   "desc": "1870–1905 · \"salon2\" architecture · 5 works.",
   "deg": 7,
   "size": 3.19
  },
  {
   "id": "art:eu-33",
   "label": "Impression, Sunrise",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Claude Monet — 1872",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-34",
   "label": "Bal du moulin de la Galette",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Pierre-Auguste Renoir — 1876",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-35",
   "label": "A Sunday Afternoon on the Island of La Grande Jatte",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Georges Seurat — 1884–1886",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-36",
   "label": "The Starry Night",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Vincent van Gogh — 1889",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-37",
   "label": "Water Lilies",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Claude Monet — c. 1906",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "era:euromodern",
   "label": "The Modern Era",
   "cat": "concept",
   "desc": "1890–1930 · \"euromodern\" architecture · 3 works.",
   "deg": 5,
   "size": 3.01
  },
  {
   "id": "art:eu-38",
   "label": "The Scream",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Edvard Munch — 1893",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-39",
   "label": "The Kiss",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Gustav Klimt — 1907–1908",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:eu-40",
   "label": "Composition II in Red, Blue, and Yellow",
   "cat": "art",
   "path": "js/data/europe.js",
   "desc": "Piet Mondrian — 1930",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "wing:africa",
   "label": "Africa Wing",
   "cat": "concept",
   "desc": "Hall at -15° from the rotunda — 20 works, moving forward in time.",
   "deg": 6,
   "size": 3.1
  },
  {
   "id": "era:egypt",
   "label": "Ancient Egypt",
   "cat": "concept",
   "desc": "3100 BCE – 300 CE · \"egypt\" architecture · 8 works.",
   "deg": 11,
   "size": 3.49
  },
  {
   "id": "art:af-01",
   "label": "Narmer Palette",
   "cat": "art",
   "path": "js/data/africa.js",
   "desc": "Early Dynastic Egypt — c. 3100 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:af-02",
   "label": "The Great Sphinx of Giza",
   "cat": "art",
   "path": "js/data/africa.js",
   "desc": "Old Kingdom Egypt, reign of Khafre — c. 2550 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:af-03",
   "label": "The Seated Scribe",
   "cat": "art",
   "path": "js/data/africa.js",
   "desc": "Old Kingdom Egypt, Saqqara — c. 2500 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:af-04",
   "label": "Nebamun Hunting in the Marshes",
   "cat": "art",
   "path": "js/data/africa.js",
   "desc": "New Kingdom Egypt, Thebes — c. 1350 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:af-05",
   "label": "Bust of Nefertiti",
   "cat": "art",
   "path": "js/data/africa.js",
   "desc": "Thutmose, Amarna — c. 1345 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:af-06",
   "label": "Funerary Mask of Tutankhamun",
   "cat": "art",
   "path": "js/data/africa.js",
   "desc": "New Kingdom Egypt — c. 1323 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:af-07",
   "label": "Book of the Dead of Hunefer",
   "cat": "art",
   "path": "js/data/africa.js",
   "desc": "New Kingdom Egypt, Thebes — c. 1275 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:af-08",
   "label": "Fayum Mummy Portrait",
   "cat": "art",
   "path": "js/data/africa.js",
   "desc": "Roman Egypt — c. 100–150 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "era:kingdoms",
   "label": "Kingdoms of Africa",
   "cat": "concept",
   "desc": "500 BCE – 1600 CE · \"sahel\" architecture · 7 works.",
   "deg": 10,
   "size": 3.42
  },
  {
   "id": "art:af-09",
   "label": "Pyramids of Meroë",
   "cat": "art",
   "path": "js/data/africa.js",
   "desc": "Kingdom of Kush, Sudan — c. 300 BCE – 350 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:af-10",
   "label": "Nok Terracotta Head",
   "cat": "art",
   "path": "js/data/africa.js",
   "desc": "Nok culture, Nigeria — c. 500 BCE – 200 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:af-11",
   "label": "Bronze Head from Ife",
   "cat": "art",
   "path": "js/data/africa.js",
   "desc": "Yoruba, Kingdom of Ife, Nigeria — c. 1300–1450 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:af-12",
   "label": "Benin Bronze Plaque",
   "cat": "art",
   "path": "js/data/africa.js",
   "desc": "Edo peoples, Kingdom of Benin — 16th–17th century CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:af-13",
   "label": "Queen Idia Ivory Mask",
   "cat": "art",
   "path": "js/data/africa.js",
   "desc": "Edo peoples, Kingdom of Benin — early 16th century CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:af-14",
   "label": "Great Mosque of Djenné",
   "cat": "art",
   "path": "js/data/africa.js",
   "desc": "Masons of Djenné, Mali — founded 13th century CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:af-15",
   "label": "Great Zimbabwe",
   "cat": "art",
   "path": "js/data/africa.js",
   "desc": "Shona builders, Zimbabwe — 11th–15th century CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "era:traditions",
   "label": "Faith & Living Traditions",
   "cat": "concept",
   "desc": "1200–1950 · \"earthen\" architecture · 5 works.",
   "deg": 8,
   "size": 3.27
  },
  {
   "id": "art:af-16",
   "label": "Church of Saint George, Lalibela",
   "cat": "art",
   "path": "js/data/africa.js",
   "desc": "Zagwe dynasty, Ethiopia — c. 1200 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:af-17",
   "label": "Ethiopian Double Diptych Icon",
   "cat": "art",
   "path": "js/data/africa.js",
   "desc": "Ethiopian Orthodox painters — 17th century CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:af-18",
   "label": "Nkisi Nkondi Power Figure",
   "cat": "art",
   "path": "js/data/africa.js",
   "desc": "Kongo peoples, Central Africa — 19th century CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:af-19",
   "label": "Kuba Cloth",
   "cat": "art",
   "path": "js/data/africa.js",
   "desc": "Kuba peoples, D.R. Congo — 19th–20th century CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:af-20",
   "label": "Dan Mask",
   "cat": "art",
   "path": "js/data/africa.js",
   "desc": "Dan peoples, Liberia and Côte d'Ivoire — 19th–20th century CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "wing:middleeast",
   "label": "The Middle East Wing",
   "cat": "concept",
   "desc": "Hall at 15° from the rotunda — 40 works, moving forward in time.",
   "deg": 9,
   "size": 3.35
  },
  {
   "id": "era:neolithic",
   "label": "The First Villages",
   "cat": "concept",
   "desc": "9500–5000 BCE · \"neolithic\" architecture · 4 works.",
   "deg": 6,
   "size": 3.1
  },
  {
   "id": "art:me-01",
   "label": "Göbekli Tepe",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Pre-Pottery Neolithic builders, Anatolia — c. 9500 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-02",
   "label": "The Jericho Skull",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Neolithic Levant — c. 8000 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-03",
   "label": "ʿAin Ghazal Statues",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Neolithic Jordan — c. 7000 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-04",
   "label": "Seated Woman of Çatalhöyük",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Neolithic Anatolia — c. 6000 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "era:mesopotamia",
   "label": "Mesopotamia",
   "cat": "concept",
   "desc": "3100–539 BCE · \"mesopotamia\" architecture · 11 works.",
   "deg": 14,
   "size": 3.68
  },
  {
   "id": "art:me-05",
   "label": "The Mask of Warka",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Sumerian, Uruk — c. 3100 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-06",
   "label": "Votive Statues of Tell Asmar",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Sumerian, Eshnunna — c. 2700 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-07",
   "label": "The Standard of Ur",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Sumerian, Ur — c. 2600 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-08",
   "label": "Ram in a Thicket",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Sumerian, Royal Cemetery of Ur — c. 2600 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-09",
   "label": "Victory Stele of Naram-Sin",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Akkadian Empire — c. 2250 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-10",
   "label": "Statue of Gudea",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Neo-Sumerian, Lagash — c. 2090 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-11",
   "label": "Code of Hammurabi",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Babylonian Empire — c. 1754 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-12",
   "label": "Queen of the Night Relief",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Old Babylonian — c. 1750 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-13",
   "label": "Lamassu: Human-Headed Winged Bull",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Neo-Assyrian, Khorsabad — c. 710 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-14",
   "label": "Ashurbanipal's Lion Hunt",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Neo-Assyrian, Nineveh — c. 645 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-15",
   "label": "The Ishtar Gate",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Neo-Babylonian, reign of Nebuchadnezzar II — c. 575 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "era:persia",
   "label": "Persia & the Classical East",
   "cat": "concept",
   "desc": "550 BCE – 630 CE · \"persia\" architecture · 8 works.",
   "deg": 11,
   "size": 3.49
  },
  {
   "id": "art:me-16",
   "label": "The Cyrus Cylinder",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Achaemenid Persia, Babylon — c. 539 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-17",
   "label": "Frieze of Archers, Palace of Darius",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Achaemenid Persia, Susa — c. 510 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-18",
   "label": "Apadana Reliefs, Persepolis",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Achaemenid Persia — c. 500 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-19",
   "label": "Golden Chariot of the Oxus Treasure",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Achaemenid Persia — 5th–4th century BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-20",
   "label": "Al-Khazneh (The Treasury), Petra",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Nabataean Kingdom, Jordan — c. 1st century CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-21",
   "label": "Palmyrene Funerary Relief",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Palmyra, Syria — c. 150–200 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-22",
   "label": "The Great Isaiah Scroll",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Judean scribes, Qumran — c. 125 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-23",
   "label": "Sasanian Silver Plate: The Royal Hunt",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Sasanian Persia — c. 400–500 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "era:islamic",
   "label": "The Islamic Golden Age",
   "cat": "concept",
   "desc": "650–1500 · \"islamic\" architecture · 9 works.",
   "deg": 12,
   "size": 3.56
  },
  {
   "id": "art:me-24",
   "label": "Dome of the Rock",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Umayyad Caliphate, Jerusalem — 691 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-25",
   "label": "The Blue Qur'an",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Probably Kairouan, Tunisia — c. 850–950 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-26",
   "label": "Samanid Bowl with Kufic Blessing",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Nishapur or Samarkand — 10th century CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-27",
   "label": "The Scholars' Library — Maqamat of al-Hariri",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Yahya al-Wasiti, Baghdad — 1237 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-28",
   "label": "The Elephant Clock of al-Jazari",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Ismail al-Jazari, Artuqid court — 1206 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-29",
   "label": "Persian Brass Astrolabe",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Persian instrument makers — 13th–18th century CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-30",
   "label": "Mihrab from the Madrasa Imami, Isfahan",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Isfahan, Iran — 1354–1355 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-31",
   "label": "Court of the Lions, Alhambra",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Nasrid dynasty, Granada — 1362–1391 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-32",
   "label": "The Construction of Khavarnaq Castle",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Kamal ud-Din Behzad, Herat — c. 1494 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "era:ottoman",
   "label": "Ottoman & Safavid Empires",
   "cat": "concept",
   "desc": "1500–1900 · \"ottoman\" architecture · 6 works.",
   "deg": 8,
   "size": 3.27
  },
  {
   "id": "art:me-33",
   "label": "The Court of Gayumars",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Sultan Muhammad, Tabriz — c. 1522–1525 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-34",
   "label": "The Ardabil Carpet",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Safavid workshop, probably Tabriz — 1539–1540 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-35",
   "label": "Tughra of Suleiman the Magnificent",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Ottoman court calligraphers — c. 1555 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-36",
   "label": "Iznik Dish",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Iznik potters, Ottoman Turkey — c. 1570 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-37",
   "label": "Süleymaniye Mosque",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Mimar Sinan, Istanbul — 1550–1557 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-38",
   "label": "Khusraw Discovers Shirin Bathing",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Safavid Persia, after Nizami — 16th century CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "era:memodern",
   "label": "Into the Modern Era",
   "cat": "concept",
   "desc": "1850–1950 · \"memodern\" architecture · 2 works.",
   "deg": 5,
   "size": 3.01
  },
  {
   "id": "art:me-39",
   "label": "The Tortoise Trainer",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Osman Hamdi Bey — 1906",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:me-40",
   "label": "The Mirror Hall",
   "cat": "art",
   "path": "js/data/middleeast.js",
   "desc": "Kamal-ol-Molk — 1896",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "wing:asia",
   "label": "Asia Wing",
   "cat": "concept",
   "desc": "Hall at 45° from the rotunda — 30 works, moving forward in time.",
   "deg": 9,
   "size": 3.35
  },
  {
   "id": "era:indus",
   "label": "Indus Valley & Early India",
   "cat": "concept",
   "desc": "2500 BCE – 500 CE · \"indus\" architecture · 4 works.",
   "deg": 7,
   "size": 3.19
  },
  {
   "id": "art:as-01",
   "label": "Dancing Girl of Mohenjo-daro",
   "cat": "art",
   "path": "js/data/asia.js",
   "desc": "Indus Valley Civilization — c. 2500 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:as-02",
   "label": "The Priest-King of Mohenjo-daro",
   "cat": "art",
   "path": "js/data/asia.js",
   "desc": "Indus Valley Civilization — c. 2000 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:as-03",
   "label": "The Great Stupa at Sanchi",
   "cat": "art",
   "path": "js/data/asia.js",
   "desc": "Maurya and Satavahana dynasties, India — 3rd century BCE – 1st century CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:as-04",
   "label": "Padmapani, Ajanta Caves",
   "cat": "art",
   "path": "js/data/asia.js",
   "desc": "Unknown, Vakataka dynasty, India — c. 478 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "era:china",
   "label": "China & Korea",
   "cat": "concept",
   "desc": "1200 BCE – 1600 CE · \"china\" architecture · 9 works.",
   "deg": 12,
   "size": 3.56
  },
  {
   "id": "art:as-05",
   "label": "Houmuwu Ding",
   "cat": "art",
   "path": "js/data/asia.js",
   "desc": "Shang dynasty, China — c. 1200 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:as-06",
   "label": "The Terracotta Army",
   "cat": "art",
   "path": "js/data/asia.js",
   "desc": "Qin dynasty, China — c. 210 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:as-07",
   "label": "Travelers Among Mountains and Streams",
   "cat": "art",
   "path": "js/data/asia.js",
   "desc": "Fan Kuan — c. 1000 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:as-08",
   "label": "A Thousand Li of Rivers and Mountains",
   "cat": "art",
   "path": "js/data/asia.js",
   "desc": "Wang Ximeng — 1113 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:as-09",
   "label": "Along the River During the Qingming Festival",
   "cat": "art",
   "path": "js/data/asia.js",
   "desc": "Zhang Zeduan — early 12th century CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:as-10",
   "label": "Nine Dragons",
   "cat": "art",
   "path": "js/data/asia.js",
   "desc": "Chen Rong — 1244 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:as-11",
   "label": "Goryeo Celadon Prunus Vase",
   "cat": "art",
   "path": "js/data/asia.js",
   "desc": "Goryeo dynasty, Korea — 12th century CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:as-12",
   "label": "The David Vases",
   "cat": "art",
   "path": "js/data/asia.js",
   "desc": "Jingdezhen kilns, Yuan dynasty, China — 1351 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:as-13",
   "label": "Irworobongdo: Sun, Moon, and Five Peaks",
   "cat": "art",
   "path": "js/data/asia.js",
   "desc": "Joseon court painters, Korea — 19th century CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "era:seasia",
   "label": "Southeast Asia",
   "cat": "concept",
   "desc": "850–1300 · \"khmer\" architecture · 3 works.",
   "deg": 6,
   "size": 3.1
  },
  {
   "id": "art:as-14",
   "label": "Borobudur",
   "cat": "art",
   "path": "js/data/asia.js",
   "desc": "Sailendra dynasty, Java — c. 850 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:as-15",
   "label": "Angkor Wat",
   "cat": "art",
   "path": "js/data/asia.js",
   "desc": "Khmer Empire, reign of Suryavarman II — early 12th century CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:as-16",
   "label": "Face Towers of the Bayon",
   "cat": "art",
   "path": "js/data/asia.js",
   "desc": "Khmer Empire, reign of Jayavarman VII — c. 1200 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "era:japan",
   "label": "Japan",
   "cat": "concept",
   "desc": "1250–1860 · \"japan\" architecture · 6 works.",
   "deg": 9,
   "size": 3.35
  },
  {
   "id": "art:as-17",
   "label": "Great Buddha of Kamakura",
   "cat": "art",
   "path": "js/data/asia.js",
   "desc": "Kamakura period, Japan — 1252 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:as-18",
   "label": "Wind God and Thunder God",
   "cat": "art",
   "path": "js/data/asia.js",
   "desc": "Tawaraya Sōtatsu — c. 1630 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:as-19",
   "label": "Pine Trees",
   "cat": "art",
   "path": "js/data/asia.js",
   "desc": "Hasegawa Tōhaku — c. 1595 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:as-20",
   "label": "Irises",
   "cat": "art",
   "path": "js/data/asia.js",
   "desc": "Ogata Kōrin — c. 1701 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:as-21",
   "label": "The Great Wave off Kanagawa",
   "cat": "art",
   "path": "js/data/asia.js",
   "desc": "Katsushika Hokusai — c. 1831",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:as-22",
   "label": "Sudden Shower over Shin-Ōhashi Bridge",
   "cat": "art",
   "path": "js/data/asia.js",
   "desc": "Utagawa Hiroshige — 1857",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "era:southasia",
   "label": "Mughal & South Asia",
   "cat": "concept",
   "desc": "700–1800 · \"mughal\" architecture · 5 works.",
   "deg": 8,
   "size": 3.27
  },
  {
   "id": "art:as-23",
   "label": "Shiva Nataraja, Lord of the Dance",
   "cat": "art",
   "path": "js/data/asia.js",
   "desc": "Chola dynasty, Tamil Nadu, India — c. 11th century CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:as-24",
   "label": "Kailasa Temple, Ellora",
   "cat": "art",
   "path": "js/data/asia.js",
   "desc": "Rashtrakuta dynasty, India — 8th century CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:as-25",
   "label": "Jahangir Preferring a Sufi Shaikh to Kings",
   "cat": "art",
   "path": "js/data/asia.js",
   "desc": "Bichitr, Mughal court — c. 1618 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:as-26",
   "label": "Taj Mahal",
   "cat": "art",
   "path": "js/data/asia.js",
   "desc": "Ustad Ahmad Lahauri for Shah Jahan — 1632–1653 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:as-27",
   "label": "Radha and Krishna in the Grove",
   "cat": "art",
   "path": "js/data/asia.js",
   "desc": "Pahari school, Kangra, India — c. 1780 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "era:asiamodern",
   "label": "Into the Modern Era",
   "cat": "concept",
   "desc": "1850–1950 · \"asiamodern\" architecture · 3 works.",
   "deg": 5,
   "size": 3.01
  },
  {
   "id": "art:as-28",
   "label": "Shakuntala",
   "cat": "art",
   "path": "js/data/asia.js",
   "desc": "Raja Ravi Varma — 1870",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:as-29",
   "label": "Bharat Mata (Mother India)",
   "cat": "art",
   "path": "js/data/asia.js",
   "desc": "Abanindranath Tagore — 1905",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:as-30",
   "label": "Fireworks at Ikenohata",
   "cat": "art",
   "path": "js/data/asia.js",
   "desc": "Kobayashi Kiyochika — 1881",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "wing:oceania",
   "label": "Oceania Wing",
   "cat": "concept",
   "desc": "Hall at 75° from the rotunda — 12 works, moving forward in time.",
   "deg": 6,
   "size": 3.1
  },
  {
   "id": "era:oceancient",
   "label": "Ancient Oceania",
   "cat": "concept",
   "desc": "28,000 BCE – 1200 CE · \"rockshelter\" architecture · 4 works.",
   "deg": 7,
   "size": 3.19
  },
  {
   "id": "art:oc-01",
   "label": "Gwion Gwion Rock Paintings",
   "cat": "art",
   "path": "js/data/oceania.js",
   "desc": "Aboriginal artists, the Kimberley, Australia — c. 10,000 BCE or earlier",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:oc-02",
   "label": "X-ray Rock Art of Kakadu",
   "cat": "art",
   "path": "js/data/oceania.js",
   "desc": "Bininj artists, Arnhem Land, Australia — c. 2000 BCE – 1900 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:oc-03",
   "label": "Uluru",
   "cat": "art",
   "path": "js/data/oceania.js",
   "desc": "Sacred site of the Aṉangu people, Australia — sacred across millennia",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:oc-04",
   "label": "Lapita Pottery",
   "cat": "art",
   "path": "js/data/oceania.js",
   "desc": "Lapita culture, Melanesia and Western Polynesia — c. 1300–800 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "era:ocevoyage",
   "label": "Voyagers of the Pacific",
   "cat": "concept",
   "desc": "1200–1800 · \"oceanic\" architecture · 5 works.",
   "deg": 8,
   "size": 3.27
  },
  {
   "id": "art:oc-05",
   "label": "Moai of Rapa Nui (Easter Island)",
   "cat": "art",
   "path": "js/data/oceania.js",
   "desc": "Rapa Nui people — c. 1250–1500 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:oc-06",
   "label": "Rai Stones of Yap",
   "cat": "art",
   "path": "js/data/oceania.js",
   "desc": "Yapese people, Micronesia — c. 1000–1900 CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:oc-07",
   "label": "Hei-tiki Pendant",
   "cat": "art",
   "path": "js/data/oceania.js",
   "desc": "Māori carvers, Aotearoa New Zealand — 18th–19th century CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:oc-08",
   "label": "Kūka'ilimoku, God of War",
   "cat": "art",
   "path": "js/data/oceania.js",
   "desc": "Hawaiian carvers — late 18th century CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:oc-09",
   "label": "ʻAhu ʻula — Hawaiian Feather Cloak",
   "cat": "art",
   "path": "js/data/oceania.js",
   "desc": "Hawaiian feather workers — 18th–19th century CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "era:oceliving",
   "label": "Living Traditions",
   "cat": "concept",
   "desc": "1800–1950 · \"oceanic2\" architecture · 3 works.",
   "deg": 6,
   "size": 3.1
  },
  {
   "id": "art:oc-10",
   "label": "Poupou — Māori Meeting House Carving",
   "cat": "art",
   "path": "js/data/oceania.js",
   "desc": "Māori carvers, Aotearoa New Zealand — 19th century CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:oc-11",
   "label": "Bis Poles of the Asmat",
   "cat": "art",
   "path": "js/data/oceania.js",
   "desc": "Asmat carvers, New Guinea — early 20th century CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:oc-12",
   "label": "Malagan Carving",
   "cat": "art",
   "path": "js/data/oceania.js",
   "desc": "New Ireland carvers, Papua New Guinea — 19th–20th century CE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:pre-01",
   "label": "Lion-Man of Hohlenstein-Stadel",
   "cat": "art",
   "path": "js/data/prehistoric.js",
   "desc": "Unknown, Upper Paleolithic — c. 38,000 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:pre-02",
   "label": "Horses of Chauvet Cave",
   "cat": "art",
   "path": "js/data/prehistoric.js",
   "desc": "Unknown, Upper Paleolithic — c. 30,000 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:pre-03",
   "label": "Venus of Willendorf",
   "cat": "art",
   "path": "js/data/prehistoric.js",
   "desc": "Unknown, Upper Paleolithic — c. 28,000 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:pre-04",
   "label": "Venus of Brassempouy",
   "cat": "art",
   "path": "js/data/prehistoric.js",
   "desc": "Unknown, Upper Paleolithic — c. 23,000 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:pre-05",
   "label": "Hall of the Bulls, Lascaux",
   "cat": "art",
   "path": "js/data/prehistoric.js",
   "desc": "Unknown, Upper Paleolithic — c. 17,000 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:pre-06",
   "label": "Bison of Altamira",
   "cat": "art",
   "path": "js/data/prehistoric.js",
   "desc": "Unknown, Upper Paleolithic — c. 15,000 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:pre-07",
   "label": "Cueva de las Manos",
   "cat": "art",
   "path": "js/data/prehistoric.js",
   "desc": "Unknown hunter-gatherers, Patagonia — c. 7,300 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:pre-08",
   "label": "Rock Shelters of Bhimbetka",
   "cat": "art",
   "path": "js/data/prehistoric.js",
   "desc": "Unknown, Mesolithic India — c. 8,000 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:pre-09",
   "label": "Saharan Rock Art of Tadrart Acacus",
   "cat": "art",
   "path": "js/data/prehistoric.js",
   "desc": "Unknown, Neolithic Sahara — c. 7,000 BCE",
   "deg": 1,
   "size": 1.3
  },
  {
   "id": "art:pre-10",
   "label": "Stonehenge",
   "cat": "art",
   "path": "js/data/prehistoric.js",
   "desc": "Unknown, Neolithic Britain — c. 2,500 BCE",
   "deg": 1,
   "size": 1.3
  }
 ],
 "edges": [
  {
   "s": "js/art.js",
   "t": "lib:three",
   "type": "imports"
  },
  {
   "s": "js/art.js",
   "t": "js/data/imageUrls.js",
   "type": "imports"
  },
  {
   "s": "js/art.js",
   "t": "js/data/imageLocal.js",
   "type": "imports"
  },
  {
   "s": "js/art.js",
   "t": "js/textures.js",
   "type": "imports"
  },
  {
   "s": "js/art.js",
   "t": "js/styles.js",
   "type": "imports"
  },
  {
   "s": "js/art.js",
   "t": "js/device.js",
   "type": "imports"
  },
  {
   "s": "js/controls.js",
   "t": "lib:three",
   "type": "imports"
  },
  {
   "s": "js/corridor.js",
   "t": "lib:three",
   "type": "imports"
  },
  {
   "s": "js/corridor.js",
   "t": "js/textures.js",
   "type": "imports"
  },
  {
   "s": "js/corridor.js",
   "t": "js/models.js",
   "type": "imports"
  },
  {
   "s": "js/corridor.js",
   "t": "js/fire.js",
   "type": "imports"
  },
  {
   "s": "js/fire.js",
   "t": "lib:three",
   "type": "imports"
  },
  {
   "s": "js/fire.js",
   "t": "js/textures.js",
   "type": "imports"
  },
  {
   "s": "js/main.js",
   "t": "lib:three",
   "type": "imports"
  },
  {
   "s": "js/main.js",
   "t": "js/world.js",
   "type": "imports"
  },
  {
   "s": "js/main.js",
   "t": "js/art.js",
   "type": "imports"
  },
  {
   "s": "js/main.js",
   "t": "js/controls.js",
   "type": "imports"
  },
  {
   "s": "js/main.js",
   "t": "js/ui.js",
   "type": "imports"
  },
  {
   "s": "js/main.js",
   "t": "js/audio.js",
   "type": "imports"
  },
  {
   "s": "js/main.js",
   "t": "js/device.js",
   "type": "imports"
  },
  {
   "s": "js/main.js",
   "t": "js/persist.js",
   "type": "imports"
  },
  {
   "s": "js/models.js",
   "t": "lib:three",
   "type": "imports"
  },
  {
   "s": "js/styles.js",
   "t": "lib:three",
   "type": "imports"
  },
  {
   "s": "js/styles.js",
   "t": "js/textures.js",
   "type": "imports"
  },
  {
   "s": "js/textures.js",
   "t": "lib:three",
   "type": "imports"
  },
  {
   "s": "js/ui.js",
   "t": "js/data/imageUrls.js",
   "type": "imports"
  },
  {
   "s": "js/ui.js",
   "t": "js/data/imageLocal.js",
   "type": "imports"
  },
  {
   "s": "js/ui.js",
   "t": "js/data/artworks.js",
   "type": "imports"
  },
  {
   "s": "js/world.js",
   "t": "lib:three",
   "type": "imports"
  },
  {
   "s": "js/world.js",
   "t": "js/data/artworks.js",
   "type": "imports"
  },
  {
   "s": "js/world.js",
   "t": "js/styles.js",
   "type": "imports"
  },
  {
   "s": "js/world.js",
   "t": "js/corridor.js",
   "type": "imports"
  },
  {
   "s": "js/world.js",
   "t": "js/textures.js",
   "type": "imports"
  },
  {
   "s": "js/world.js",
   "t": "js/fire.js",
   "type": "imports"
  },
  {
   "s": "js/world.js",
   "t": "js/models.js",
   "type": "imports"
  },
  {
   "s": "js/data/artworks.js",
   "t": "js/data/prehistoric.js",
   "type": "imports"
  },
  {
   "s": "js/data/artworks.js",
   "t": "js/data/americas.js",
   "type": "imports"
  },
  {
   "s": "js/data/artworks.js",
   "t": "js/data/europe.js",
   "type": "imports"
  },
  {
   "s": "js/data/artworks.js",
   "t": "js/data/middleeast.js",
   "type": "imports"
  },
  {
   "s": "js/data/artworks.js",
   "t": "js/data/asia.js",
   "type": "imports"
  },
  {
   "s": "js/data/artworks.js",
   "t": "js/data/africa.js",
   "type": "imports"
  },
  {
   "s": "js/data/artworks.js",
   "t": "js/data/oceania.js",
   "type": "imports"
  },
  {
   "s": "concept:museum",
   "t": "concept:rotunda",
   "type": "contains"
  },
  {
   "s": "concept:museum",
   "t": "concept:cave",
   "type": "contains"
  },
  {
   "s": "js/world.js",
   "t": "concept:museum",
   "type": "creates"
  },
  {
   "s": "js/world.js",
   "t": "concept:rotunda",
   "type": "creates"
  },
  {
   "s": "js/world.js",
   "t": "concept:cave",
   "type": "creates"
  },
  {
   "s": "js/corridor.js",
   "t": "concept:portals",
   "type": "creates"
  },
  {
   "s": "js/controls.js",
   "t": "concept:player",
   "type": "creates"
  },
  {
   "s": "js/styles.js",
   "t": "concept:styles",
   "type": "creates"
  },
  {
   "s": "js/ui.js",
   "t": "concept:hud",
   "type": "creates"
  },
  {
   "s": "js/audio.js",
   "t": "concept:audio",
   "type": "creates"
  },
  {
   "s": "js/persist.js",
   "t": "concept:save",
   "type": "creates"
  },
  {
   "s": "js/device.js",
   "t": "concept:quality",
   "type": "creates"
  },
  {
   "s": "js/fire.js",
   "t": "concept:fires",
   "type": "creates"
  },
  {
   "s": "js/data/artworks.js",
   "t": "concept:museum",
   "type": "configures"
  },
  {
   "s": "concept:kits",
   "t": "kit:adobe",
   "type": "contains"
  },
  {
   "s": "concept:kits",
   "t": "kit:amsalon",
   "type": "contains"
  },
  {
   "s": "concept:kits",
   "t": "kit:baroque",
   "type": "contains"
  },
  {
   "s": "concept:kits",
   "t": "kit:china",
   "type": "contains"
  },
  {
   "s": "concept:kits",
   "t": "kit:egypt",
   "type": "contains"
  },
  {
   "s": "concept:kits",
   "t": "kit:gothic",
   "type": "contains"
  },
  {
   "s": "concept:kits",
   "t": "kit:greek",
   "type": "contains"
  },
  {
   "s": "concept:kits",
   "t": "kit:inca",
   "type": "contains"
  },
  {
   "s": "concept:kits",
   "t": "kit:indus",
   "type": "contains"
  },
  {
   "s": "concept:kits",
   "t": "kit:islamic",
   "type": "contains"
  },
  {
   "s": "concept:kits",
   "t": "kit:japan",
   "type": "contains"
  },
  {
   "s": "concept:kits",
   "t": "kit:khmer",
   "type": "contains"
  },
  {
   "s": "concept:kits",
   "t": "kit:kingdoms",
   "type": "contains"
  },
  {
   "s": "concept:kits",
   "t": "kit:meso",
   "type": "contains"
  },
  {
   "s": "concept:kits",
   "t": "kit:mesopotamia",
   "type": "contains"
  },
  {
   "s": "concept:kits",
   "t": "kit:modern",
   "type": "contains"
  },
  {
   "s": "concept:kits",
   "t": "kit:mughal",
   "type": "contains"
  },
  {
   "s": "concept:kits",
   "t": "kit:oceanic",
   "type": "contains"
  },
  {
   "s": "concept:kits",
   "t": "kit:persia",
   "type": "contains"
  },
  {
   "s": "concept:kits",
   "t": "kit:prehistoric",
   "type": "contains"
  },
  {
   "s": "concept:kits",
   "t": "kit:renaissance",
   "type": "contains"
  },
  {
   "s": "concept:kits",
   "t": "kit:rockshelter",
   "type": "contains"
  },
  {
   "s": "concept:kits",
   "t": "kit:salon",
   "type": "contains"
  },
  {
   "s": "concept:kits",
   "t": "kit:traditions",
   "type": "contains"
  },
  {
   "s": "js/models.js",
   "t": "concept:kits",
   "type": "loads"
  },
  {
   "s": "js/world.js",
   "t": "kit:prehistoric",
   "type": "loads"
  },
  {
   "s": "js/textures.js",
   "t": "asset:texfiles",
   "type": "loads"
  },
  {
   "s": "js/art.js",
   "t": "asset:wikimedia",
   "type": "loads"
  },
  {
   "s": "js/art.js",
   "t": "asset:localart",
   "type": "loads"
  },
  {
   "s": "js/data/imageUrls.js",
   "t": "asset:wikimedia",
   "type": "loads"
  },
  {
   "s": "js/data/imageLocal.js",
   "t": "asset:localart",
   "type": "loads"
  },
  {
   "s": "concept:museum",
   "t": "wing:americas",
   "type": "contains"
  },
  {
   "s": "js/world.js",
   "t": "wing:americas",
   "type": "creates"
  },
  {
   "s": "js/data/americas.js",
   "t": "wing:americas",
   "type": "configures"
  },
  {
   "s": "wing:americas",
   "t": "era:mesoamerica",
   "type": "contains"
  },
  {
   "s": "js/corridor.js",
   "t": "era:mesoamerica",
   "type": "creates"
  },
  {
   "s": "era:mesoamerica",
   "t": "kit:meso",
   "type": "loads"
  },
  {
   "s": "era:mesoamerica",
   "t": "art:am-01",
   "type": "contains"
  },
  {
   "s": "era:mesoamerica",
   "t": "art:am-02",
   "type": "contains"
  },
  {
   "s": "era:mesoamerica",
   "t": "art:am-03",
   "type": "contains"
  },
  {
   "s": "era:mesoamerica",
   "t": "art:am-04",
   "type": "contains"
  },
  {
   "s": "era:mesoamerica",
   "t": "art:am-05",
   "type": "contains"
  },
  {
   "s": "era:mesoamerica",
   "t": "art:am-06",
   "type": "contains"
  },
  {
   "s": "era:mesoamerica",
   "t": "art:am-07",
   "type": "contains"
  },
  {
   "s": "wing:americas",
   "t": "era:andes",
   "type": "contains"
  },
  {
   "s": "js/corridor.js",
   "t": "era:andes",
   "type": "creates"
  },
  {
   "s": "era:andes",
   "t": "kit:inca",
   "type": "loads"
  },
  {
   "s": "era:andes",
   "t": "art:am-08",
   "type": "contains"
  },
  {
   "s": "era:andes",
   "t": "art:am-09",
   "type": "contains"
  },
  {
   "s": "era:andes",
   "t": "art:am-10",
   "type": "contains"
  },
  {
   "s": "era:andes",
   "t": "art:am-11",
   "type": "contains"
  },
  {
   "s": "wing:americas",
   "t": "era:nativenorth",
   "type": "contains"
  },
  {
   "s": "js/corridor.js",
   "t": "era:nativenorth",
   "type": "creates"
  },
  {
   "s": "era:nativenorth",
   "t": "kit:adobe",
   "type": "loads"
  },
  {
   "s": "era:nativenorth",
   "t": "art:am-12",
   "type": "contains"
  },
  {
   "s": "era:nativenorth",
   "t": "art:am-13",
   "type": "contains"
  },
  {
   "s": "wing:americas",
   "t": "era:americas19",
   "type": "contains"
  },
  {
   "s": "js/corridor.js",
   "t": "era:americas19",
   "type": "creates"
  },
  {
   "s": "era:americas19",
   "t": "kit:amsalon",
   "type": "loads"
  },
  {
   "s": "era:americas19",
   "t": "art:am-14",
   "type": "contains"
  },
  {
   "s": "era:americas19",
   "t": "art:am-15",
   "type": "contains"
  },
  {
   "s": "era:americas19",
   "t": "art:am-16",
   "type": "contains"
  },
  {
   "s": "era:americas19",
   "t": "art:am-17",
   "type": "contains"
  },
  {
   "s": "wing:americas",
   "t": "era:americasmodern",
   "type": "contains"
  },
  {
   "s": "js/corridor.js",
   "t": "era:americasmodern",
   "type": "creates"
  },
  {
   "s": "era:americasmodern",
   "t": "kit:modern",
   "type": "loads"
  },
  {
   "s": "era:americasmodern",
   "t": "art:am-18",
   "type": "contains"
  },
  {
   "s": "era:americasmodern",
   "t": "art:am-19",
   "type": "contains"
  },
  {
   "s": "era:americasmodern",
   "t": "art:am-20",
   "type": "contains"
  },
  {
   "s": "concept:museum",
   "t": "wing:europe",
   "type": "contains"
  },
  {
   "s": "js/world.js",
   "t": "wing:europe",
   "type": "creates"
  },
  {
   "s": "js/data/europe.js",
   "t": "wing:europe",
   "type": "configures"
  },
  {
   "s": "wing:europe",
   "t": "era:classical",
   "type": "contains"
  },
  {
   "s": "js/corridor.js",
   "t": "era:classical",
   "type": "creates"
  },
  {
   "s": "era:classical",
   "t": "kit:greek",
   "type": "loads"
  },
  {
   "s": "era:classical",
   "t": "art:eu-01",
   "type": "contains"
  },
  {
   "s": "era:classical",
   "t": "art:eu-02",
   "type": "contains"
  },
  {
   "s": "era:classical",
   "t": "art:eu-03",
   "type": "contains"
  },
  {
   "s": "era:classical",
   "t": "art:eu-04",
   "type": "contains"
  },
  {
   "s": "era:classical",
   "t": "art:eu-05",
   "type": "contains"
  },
  {
   "s": "era:classical",
   "t": "art:eu-06",
   "type": "contains"
  },
  {
   "s": "wing:europe",
   "t": "era:medieval",
   "type": "contains"
  },
  {
   "s": "js/corridor.js",
   "t": "era:medieval",
   "type": "creates"
  },
  {
   "s": "era:medieval",
   "t": "kit:gothic",
   "type": "loads"
  },
  {
   "s": "era:medieval",
   "t": "art:eu-07",
   "type": "contains"
  },
  {
   "s": "era:medieval",
   "t": "art:eu-08",
   "type": "contains"
  },
  {
   "s": "era:medieval",
   "t": "art:eu-09",
   "type": "contains"
  },
  {
   "s": "era:medieval",
   "t": "art:eu-10",
   "type": "contains"
  },
  {
   "s": "era:medieval",
   "t": "art:eu-11",
   "type": "contains"
  },
  {
   "s": "wing:europe",
   "t": "era:renaissance",
   "type": "contains"
  },
  {
   "s": "js/corridor.js",
   "t": "era:renaissance",
   "type": "creates"
  },
  {
   "s": "era:renaissance",
   "t": "kit:renaissance",
   "type": "loads"
  },
  {
   "s": "era:renaissance",
   "t": "art:eu-12",
   "type": "contains"
  },
  {
   "s": "era:renaissance",
   "t": "art:eu-13",
   "type": "contains"
  },
  {
   "s": "era:renaissance",
   "t": "art:eu-14",
   "type": "contains"
  },
  {
   "s": "era:renaissance",
   "t": "art:eu-15",
   "type": "contains"
  },
  {
   "s": "era:renaissance",
   "t": "art:eu-16",
   "type": "contains"
  },
  {
   "s": "era:renaissance",
   "t": "art:eu-17",
   "type": "contains"
  },
  {
   "s": "era:renaissance",
   "t": "art:eu-18",
   "type": "contains"
  },
  {
   "s": "era:renaissance",
   "t": "art:eu-19",
   "type": "contains"
  },
  {
   "s": "era:renaissance",
   "t": "art:eu-20",
   "type": "contains"
  },
  {
   "s": "wing:europe",
   "t": "era:baroque",
   "type": "contains"
  },
  {
   "s": "js/corridor.js",
   "t": "era:baroque",
   "type": "creates"
  },
  {
   "s": "era:baroque",
   "t": "kit:baroque",
   "type": "loads"
  },
  {
   "s": "era:baroque",
   "t": "art:eu-21",
   "type": "contains"
  },
  {
   "s": "era:baroque",
   "t": "art:eu-22",
   "type": "contains"
  },
  {
   "s": "era:baroque",
   "t": "art:eu-23",
   "type": "contains"
  },
  {
   "s": "era:baroque",
   "t": "art:eu-24",
   "type": "contains"
  },
  {
   "s": "era:baroque",
   "t": "art:eu-25",
   "type": "contains"
  },
  {
   "s": "era:baroque",
   "t": "art:eu-26",
   "type": "contains"
  },
  {
   "s": "era:baroque",
   "t": "art:eu-27",
   "type": "contains"
  },
  {
   "s": "wing:europe",
   "t": "era:romantic",
   "type": "contains"
  },
  {
   "s": "js/corridor.js",
   "t": "era:romantic",
   "type": "creates"
  },
  {
   "s": "era:romantic",
   "t": "kit:salon",
   "type": "loads"
  },
  {
   "s": "era:romantic",
   "t": "art:eu-28",
   "type": "contains"
  },
  {
   "s": "era:romantic",
   "t": "art:eu-29",
   "type": "contains"
  },
  {
   "s": "era:romantic",
   "t": "art:eu-30",
   "type": "contains"
  },
  {
   "s": "era:romantic",
   "t": "art:eu-31",
   "type": "contains"
  },
  {
   "s": "era:romantic",
   "t": "art:eu-32",
   "type": "contains"
  },
  {
   "s": "wing:europe",
   "t": "era:impressionism",
   "type": "contains"
  },
  {
   "s": "js/corridor.js",
   "t": "era:impressionism",
   "type": "creates"
  },
  {
   "s": "era:impressionism",
   "t": "art:eu-33",
   "type": "contains"
  },
  {
   "s": "era:impressionism",
   "t": "art:eu-34",
   "type": "contains"
  },
  {
   "s": "era:impressionism",
   "t": "art:eu-35",
   "type": "contains"
  },
  {
   "s": "era:impressionism",
   "t": "art:eu-36",
   "type": "contains"
  },
  {
   "s": "era:impressionism",
   "t": "art:eu-37",
   "type": "contains"
  },
  {
   "s": "wing:europe",
   "t": "era:euromodern",
   "type": "contains"
  },
  {
   "s": "js/corridor.js",
   "t": "era:euromodern",
   "type": "creates"
  },
  {
   "s": "era:euromodern",
   "t": "art:eu-38",
   "type": "contains"
  },
  {
   "s": "era:euromodern",
   "t": "art:eu-39",
   "type": "contains"
  },
  {
   "s": "era:euromodern",
   "t": "art:eu-40",
   "type": "contains"
  },
  {
   "s": "concept:museum",
   "t": "wing:africa",
   "type": "contains"
  },
  {
   "s": "js/world.js",
   "t": "wing:africa",
   "type": "creates"
  },
  {
   "s": "js/data/africa.js",
   "t": "wing:africa",
   "type": "configures"
  },
  {
   "s": "wing:africa",
   "t": "era:egypt",
   "type": "contains"
  },
  {
   "s": "js/corridor.js",
   "t": "era:egypt",
   "type": "creates"
  },
  {
   "s": "era:egypt",
   "t": "kit:egypt",
   "type": "loads"
  },
  {
   "s": "era:egypt",
   "t": "art:af-01",
   "type": "contains"
  },
  {
   "s": "era:egypt",
   "t": "art:af-02",
   "type": "contains"
  },
  {
   "s": "era:egypt",
   "t": "art:af-03",
   "type": "contains"
  },
  {
   "s": "era:egypt",
   "t": "art:af-04",
   "type": "contains"
  },
  {
   "s": "era:egypt",
   "t": "art:af-05",
   "type": "contains"
  },
  {
   "s": "era:egypt",
   "t": "art:af-06",
   "type": "contains"
  },
  {
   "s": "era:egypt",
   "t": "art:af-07",
   "type": "contains"
  },
  {
   "s": "era:egypt",
   "t": "art:af-08",
   "type": "contains"
  },
  {
   "s": "wing:africa",
   "t": "era:kingdoms",
   "type": "contains"
  },
  {
   "s": "js/corridor.js",
   "t": "era:kingdoms",
   "type": "creates"
  },
  {
   "s": "era:kingdoms",
   "t": "kit:kingdoms",
   "type": "loads"
  },
  {
   "s": "era:kingdoms",
   "t": "art:af-09",
   "type": "contains"
  },
  {
   "s": "era:kingdoms",
   "t": "art:af-10",
   "type": "contains"
  },
  {
   "s": "era:kingdoms",
   "t": "art:af-11",
   "type": "contains"
  },
  {
   "s": "era:kingdoms",
   "t": "art:af-12",
   "type": "contains"
  },
  {
   "s": "era:kingdoms",
   "t": "art:af-13",
   "type": "contains"
  },
  {
   "s": "era:kingdoms",
   "t": "art:af-14",
   "type": "contains"
  },
  {
   "s": "era:kingdoms",
   "t": "art:af-15",
   "type": "contains"
  },
  {
   "s": "wing:africa",
   "t": "era:traditions",
   "type": "contains"
  },
  {
   "s": "js/corridor.js",
   "t": "era:traditions",
   "type": "creates"
  },
  {
   "s": "era:traditions",
   "t": "kit:traditions",
   "type": "loads"
  },
  {
   "s": "era:traditions",
   "t": "art:af-16",
   "type": "contains"
  },
  {
   "s": "era:traditions",
   "t": "art:af-17",
   "type": "contains"
  },
  {
   "s": "era:traditions",
   "t": "art:af-18",
   "type": "contains"
  },
  {
   "s": "era:traditions",
   "t": "art:af-19",
   "type": "contains"
  },
  {
   "s": "era:traditions",
   "t": "art:af-20",
   "type": "contains"
  },
  {
   "s": "concept:museum",
   "t": "wing:middleeast",
   "type": "contains"
  },
  {
   "s": "js/world.js",
   "t": "wing:middleeast",
   "type": "creates"
  },
  {
   "s": "js/data/middleeast.js",
   "t": "wing:middleeast",
   "type": "configures"
  },
  {
   "s": "wing:middleeast",
   "t": "era:neolithic",
   "type": "contains"
  },
  {
   "s": "js/corridor.js",
   "t": "era:neolithic",
   "type": "creates"
  },
  {
   "s": "era:neolithic",
   "t": "art:me-01",
   "type": "contains"
  },
  {
   "s": "era:neolithic",
   "t": "art:me-02",
   "type": "contains"
  },
  {
   "s": "era:neolithic",
   "t": "art:me-03",
   "type": "contains"
  },
  {
   "s": "era:neolithic",
   "t": "art:me-04",
   "type": "contains"
  },
  {
   "s": "wing:middleeast",
   "t": "era:mesopotamia",
   "type": "contains"
  },
  {
   "s": "js/corridor.js",
   "t": "era:mesopotamia",
   "type": "creates"
  },
  {
   "s": "era:mesopotamia",
   "t": "kit:mesopotamia",
   "type": "loads"
  },
  {
   "s": "era:mesopotamia",
   "t": "art:me-05",
   "type": "contains"
  },
  {
   "s": "era:mesopotamia",
   "t": "art:me-06",
   "type": "contains"
  },
  {
   "s": "era:mesopotamia",
   "t": "art:me-07",
   "type": "contains"
  },
  {
   "s": "era:mesopotamia",
   "t": "art:me-08",
   "type": "contains"
  },
  {
   "s": "era:mesopotamia",
   "t": "art:me-09",
   "type": "contains"
  },
  {
   "s": "era:mesopotamia",
   "t": "art:me-10",
   "type": "contains"
  },
  {
   "s": "era:mesopotamia",
   "t": "art:me-11",
   "type": "contains"
  },
  {
   "s": "era:mesopotamia",
   "t": "art:me-12",
   "type": "contains"
  },
  {
   "s": "era:mesopotamia",
   "t": "art:me-13",
   "type": "contains"
  },
  {
   "s": "era:mesopotamia",
   "t": "art:me-14",
   "type": "contains"
  },
  {
   "s": "era:mesopotamia",
   "t": "art:me-15",
   "type": "contains"
  },
  {
   "s": "wing:middleeast",
   "t": "era:persia",
   "type": "contains"
  },
  {
   "s": "js/corridor.js",
   "t": "era:persia",
   "type": "creates"
  },
  {
   "s": "era:persia",
   "t": "kit:persia",
   "type": "loads"
  },
  {
   "s": "era:persia",
   "t": "art:me-16",
   "type": "contains"
  },
  {
   "s": "era:persia",
   "t": "art:me-17",
   "type": "contains"
  },
  {
   "s": "era:persia",
   "t": "art:me-18",
   "type": "contains"
  },
  {
   "s": "era:persia",
   "t": "art:me-19",
   "type": "contains"
  },
  {
   "s": "era:persia",
   "t": "art:me-20",
   "type": "contains"
  },
  {
   "s": "era:persia",
   "t": "art:me-21",
   "type": "contains"
  },
  {
   "s": "era:persia",
   "t": "art:me-22",
   "type": "contains"
  },
  {
   "s": "era:persia",
   "t": "art:me-23",
   "type": "contains"
  },
  {
   "s": "wing:middleeast",
   "t": "era:islamic",
   "type": "contains"
  },
  {
   "s": "js/corridor.js",
   "t": "era:islamic",
   "type": "creates"
  },
  {
   "s": "era:islamic",
   "t": "kit:islamic",
   "type": "loads"
  },
  {
   "s": "era:islamic",
   "t": "art:me-24",
   "type": "contains"
  },
  {
   "s": "era:islamic",
   "t": "art:me-25",
   "type": "contains"
  },
  {
   "s": "era:islamic",
   "t": "art:me-26",
   "type": "contains"
  },
  {
   "s": "era:islamic",
   "t": "art:me-27",
   "type": "contains"
  },
  {
   "s": "era:islamic",
   "t": "art:me-28",
   "type": "contains"
  },
  {
   "s": "era:islamic",
   "t": "art:me-29",
   "type": "contains"
  },
  {
   "s": "era:islamic",
   "t": "art:me-30",
   "type": "contains"
  },
  {
   "s": "era:islamic",
   "t": "art:me-31",
   "type": "contains"
  },
  {
   "s": "era:islamic",
   "t": "art:me-32",
   "type": "contains"
  },
  {
   "s": "wing:middleeast",
   "t": "era:ottoman",
   "type": "contains"
  },
  {
   "s": "js/corridor.js",
   "t": "era:ottoman",
   "type": "creates"
  },
  {
   "s": "era:ottoman",
   "t": "art:me-33",
   "type": "contains"
  },
  {
   "s": "era:ottoman",
   "t": "art:me-34",
   "type": "contains"
  },
  {
   "s": "era:ottoman",
   "t": "art:me-35",
   "type": "contains"
  },
  {
   "s": "era:ottoman",
   "t": "art:me-36",
   "type": "contains"
  },
  {
   "s": "era:ottoman",
   "t": "art:me-37",
   "type": "contains"
  },
  {
   "s": "era:ottoman",
   "t": "art:me-38",
   "type": "contains"
  },
  {
   "s": "wing:middleeast",
   "t": "era:memodern",
   "type": "contains"
  },
  {
   "s": "js/corridor.js",
   "t": "era:memodern",
   "type": "creates"
  },
  {
   "s": "era:memodern",
   "t": "kit:modern",
   "type": "loads"
  },
  {
   "s": "era:memodern",
   "t": "art:me-39",
   "type": "contains"
  },
  {
   "s": "era:memodern",
   "t": "art:me-40",
   "type": "contains"
  },
  {
   "s": "concept:museum",
   "t": "wing:asia",
   "type": "contains"
  },
  {
   "s": "js/world.js",
   "t": "wing:asia",
   "type": "creates"
  },
  {
   "s": "js/data/asia.js",
   "t": "wing:asia",
   "type": "configures"
  },
  {
   "s": "wing:asia",
   "t": "era:indus",
   "type": "contains"
  },
  {
   "s": "js/corridor.js",
   "t": "era:indus",
   "type": "creates"
  },
  {
   "s": "era:indus",
   "t": "kit:indus",
   "type": "loads"
  },
  {
   "s": "era:indus",
   "t": "art:as-01",
   "type": "contains"
  },
  {
   "s": "era:indus",
   "t": "art:as-02",
   "type": "contains"
  },
  {
   "s": "era:indus",
   "t": "art:as-03",
   "type": "contains"
  },
  {
   "s": "era:indus",
   "t": "art:as-04",
   "type": "contains"
  },
  {
   "s": "wing:asia",
   "t": "era:china",
   "type": "contains"
  },
  {
   "s": "js/corridor.js",
   "t": "era:china",
   "type": "creates"
  },
  {
   "s": "era:china",
   "t": "kit:china",
   "type": "loads"
  },
  {
   "s": "era:china",
   "t": "art:as-05",
   "type": "contains"
  },
  {
   "s": "era:china",
   "t": "art:as-06",
   "type": "contains"
  },
  {
   "s": "era:china",
   "t": "art:as-07",
   "type": "contains"
  },
  {
   "s": "era:china",
   "t": "art:as-08",
   "type": "contains"
  },
  {
   "s": "era:china",
   "t": "art:as-09",
   "type": "contains"
  },
  {
   "s": "era:china",
   "t": "art:as-10",
   "type": "contains"
  },
  {
   "s": "era:china",
   "t": "art:as-11",
   "type": "contains"
  },
  {
   "s": "era:china",
   "t": "art:as-12",
   "type": "contains"
  },
  {
   "s": "era:china",
   "t": "art:as-13",
   "type": "contains"
  },
  {
   "s": "wing:asia",
   "t": "era:seasia",
   "type": "contains"
  },
  {
   "s": "js/corridor.js",
   "t": "era:seasia",
   "type": "creates"
  },
  {
   "s": "era:seasia",
   "t": "kit:khmer",
   "type": "loads"
  },
  {
   "s": "era:seasia",
   "t": "art:as-14",
   "type": "contains"
  },
  {
   "s": "era:seasia",
   "t": "art:as-15",
   "type": "contains"
  },
  {
   "s": "era:seasia",
   "t": "art:as-16",
   "type": "contains"
  },
  {
   "s": "wing:asia",
   "t": "era:japan",
   "type": "contains"
  },
  {
   "s": "js/corridor.js",
   "t": "era:japan",
   "type": "creates"
  },
  {
   "s": "era:japan",
   "t": "kit:japan",
   "type": "loads"
  },
  {
   "s": "era:japan",
   "t": "art:as-17",
   "type": "contains"
  },
  {
   "s": "era:japan",
   "t": "art:as-18",
   "type": "contains"
  },
  {
   "s": "era:japan",
   "t": "art:as-19",
   "type": "contains"
  },
  {
   "s": "era:japan",
   "t": "art:as-20",
   "type": "contains"
  },
  {
   "s": "era:japan",
   "t": "art:as-21",
   "type": "contains"
  },
  {
   "s": "era:japan",
   "t": "art:as-22",
   "type": "contains"
  },
  {
   "s": "wing:asia",
   "t": "era:southasia",
   "type": "contains"
  },
  {
   "s": "js/corridor.js",
   "t": "era:southasia",
   "type": "creates"
  },
  {
   "s": "era:southasia",
   "t": "kit:mughal",
   "type": "loads"
  },
  {
   "s": "era:southasia",
   "t": "art:as-23",
   "type": "contains"
  },
  {
   "s": "era:southasia",
   "t": "art:as-24",
   "type": "contains"
  },
  {
   "s": "era:southasia",
   "t": "art:as-25",
   "type": "contains"
  },
  {
   "s": "era:southasia",
   "t": "art:as-26",
   "type": "contains"
  },
  {
   "s": "era:southasia",
   "t": "art:as-27",
   "type": "contains"
  },
  {
   "s": "wing:asia",
   "t": "era:asiamodern",
   "type": "contains"
  },
  {
   "s": "js/corridor.js",
   "t": "era:asiamodern",
   "type": "creates"
  },
  {
   "s": "era:asiamodern",
   "t": "art:as-28",
   "type": "contains"
  },
  {
   "s": "era:asiamodern",
   "t": "art:as-29",
   "type": "contains"
  },
  {
   "s": "era:asiamodern",
   "t": "art:as-30",
   "type": "contains"
  },
  {
   "s": "concept:museum",
   "t": "wing:oceania",
   "type": "contains"
  },
  {
   "s": "js/world.js",
   "t": "wing:oceania",
   "type": "creates"
  },
  {
   "s": "js/data/oceania.js",
   "t": "wing:oceania",
   "type": "configures"
  },
  {
   "s": "wing:oceania",
   "t": "era:oceancient",
   "type": "contains"
  },
  {
   "s": "js/corridor.js",
   "t": "era:oceancient",
   "type": "creates"
  },
  {
   "s": "era:oceancient",
   "t": "kit:rockshelter",
   "type": "loads"
  },
  {
   "s": "era:oceancient",
   "t": "art:oc-01",
   "type": "contains"
  },
  {
   "s": "era:oceancient",
   "t": "art:oc-02",
   "type": "contains"
  },
  {
   "s": "era:oceancient",
   "t": "art:oc-03",
   "type": "contains"
  },
  {
   "s": "era:oceancient",
   "t": "art:oc-04",
   "type": "contains"
  },
  {
   "s": "wing:oceania",
   "t": "era:ocevoyage",
   "type": "contains"
  },
  {
   "s": "js/corridor.js",
   "t": "era:ocevoyage",
   "type": "creates"
  },
  {
   "s": "era:ocevoyage",
   "t": "kit:oceanic",
   "type": "loads"
  },
  {
   "s": "era:ocevoyage",
   "t": "art:oc-05",
   "type": "contains"
  },
  {
   "s": "era:ocevoyage",
   "t": "art:oc-06",
   "type": "contains"
  },
  {
   "s": "era:ocevoyage",
   "t": "art:oc-07",
   "type": "contains"
  },
  {
   "s": "era:ocevoyage",
   "t": "art:oc-08",
   "type": "contains"
  },
  {
   "s": "era:ocevoyage",
   "t": "art:oc-09",
   "type": "contains"
  },
  {
   "s": "wing:oceania",
   "t": "era:oceliving",
   "type": "contains"
  },
  {
   "s": "js/corridor.js",
   "t": "era:oceliving",
   "type": "creates"
  },
  {
   "s": "era:oceliving",
   "t": "kit:oceanic",
   "type": "loads"
  },
  {
   "s": "era:oceliving",
   "t": "art:oc-10",
   "type": "contains"
  },
  {
   "s": "era:oceliving",
   "t": "art:oc-11",
   "type": "contains"
  },
  {
   "s": "era:oceliving",
   "t": "art:oc-12",
   "type": "contains"
  },
  {
   "s": "js/data/prehistoric.js",
   "t": "concept:cave",
   "type": "configures"
  },
  {
   "s": "concept:cave",
   "t": "art:pre-01",
   "type": "contains"
  },
  {
   "s": "concept:cave",
   "t": "art:pre-02",
   "type": "contains"
  },
  {
   "s": "concept:cave",
   "t": "art:pre-03",
   "type": "contains"
  },
  {
   "s": "concept:cave",
   "t": "art:pre-04",
   "type": "contains"
  },
  {
   "s": "concept:cave",
   "t": "art:pre-05",
   "type": "contains"
  },
  {
   "s": "concept:cave",
   "t": "art:pre-06",
   "type": "contains"
  },
  {
   "s": "concept:cave",
   "t": "art:pre-07",
   "type": "contains"
  },
  {
   "s": "concept:cave",
   "t": "art:pre-08",
   "type": "contains"
  },
  {
   "s": "concept:cave",
   "t": "art:pre-09",
   "type": "contains"
  },
  {
   "s": "concept:cave",
   "t": "art:pre-10",
   "type": "contains"
  }
 ]
};
