#!/usr/bin/env python3
"""Localize the artwork images: download every IMAGE_URLS entry from
js/data/imageUrls.js into assets/art/<id>.<ext> and emit js/data/imageLocal.js
mapping id -> local path for every file that downloaded + verified OK.

Why: the runtime hotlinks Wikimedia, which rate-limits bursts — audits kept
catching "loading image" placeholder panels. Local files load instantly and
never 429. imageUrls.js stays untouched as the source of truth / fallback.

Wikimedia etiquette: descriptive User-Agent, low concurrency, retry with
backoff on 429/5xx. Re-runnable: existing verified files are skipped.

    python3 tools/download_artworks.py            # download missing + emit map
    python3 tools/download_artworks.py --force    # re-download everything
"""
import argparse
import re
import sys
import time
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "js" / "data" / "imageUrls.js"
OUT_DIR = ROOT / "assets" / "art"
MAP_OUT = ROOT / "js" / "data" / "imageLocal.js"

UA = ("ArtMuseumLocalizer/1.0 (personal offline museum project; "
      "hello@timrosenberg.com) python-urllib")


def parse_urls():
    src = SRC.read_text()
    return dict(re.findall(r'"([a-z]+-\d+)":\s*"(https://[^"]+)"', src))


def ext_of(url):
    m = re.search(r"\.(jpe?g|png|gif|webp)$", url, re.I)
    return (m.group(1).lower().replace("jpeg", "jpg")) if m else "jpg"


def looks_like_image(path):
    if not path.exists() or path.stat().st_size < 4096:
        return False
    head = path.open("rb").read(12)
    return head[:3] == b"\xff\xd8\xff" or head[:8] == b"\x89PNG\r\n\x1a\n" or head[:4] == b"GIF8" or head[8:12] == b"WEBP"


def fetch(url, dest, tries=4):
    for attempt in range(tries):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": UA})
            with urllib.request.urlopen(req, timeout=60) as r:
                dest.write_bytes(r.read())
            if looks_like_image(dest):
                return True
            dest.unlink(missing_ok=True)
            return False
        except Exception as exc:  # 429/5xx/timeouts: back off and retry
            wait = 3 * (attempt + 1) ** 2
            code = getattr(exc, "code", None)
            if code in (401, 403, 404):
                print(f"  HTTP {code} (permanent) {url}")
                return False
            print(f"  retry in {wait}s ({exc})")
            time.sleep(wait)
    return False


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()

    urls = parse_urls()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    ok, failed, skipped = {}, [], 0
    for i, (aid, url) in enumerate(sorted(urls.items()), 1):
        dest = OUT_DIR / f"{aid}.{ext_of(url)}"
        if not args.force and looks_like_image(dest):
            ok[aid] = dest.name
            skipped += 1
            continue
        print(f"[{i}/{len(urls)}] {aid}")
        if fetch(url, dest):
            ok[aid] = dest.name
        else:
            failed.append(aid)
        time.sleep(0.6)   # stay well under Wikimedia burst limits

    lines = [
        "// GENERATED by tools/download_artworks.py — do not edit by hand.",
        "// Local copies of the Wikimedia artwork images (assets/art/); the",
        "// runtime prefers these and falls back to IMAGE_URLS when absent,",
        "// so Wikimedia burst rate-limiting can no longer blank the frames.",
        "export const LOCAL_ART = {",
    ]
    for aid in sorted(ok):
        lines.append(f'  "{aid}": "assets/art/{ok[aid]}",')
    lines.append("};")
    MAP_OUT.write_text("\n".join(lines) + "\n")
    total_mb = sum(f.stat().st_size for f in OUT_DIR.iterdir()) / 1e6
    print(f"\nlocalized {len(ok)}/{len(urls)} (skipped existing {skipped}), "
          f"failed: {failed or 'none'}; {total_mb:.1f} MB in {OUT_DIR}")
    print(f"wrote {MAP_OUT}")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
